#!/bin/bash
#  ____            _     _                       
# |  _ \          | |   (_)                      
# | |_) | __ _ ___| |__  _ _ __   __ _           
# |  _ < / _` / __| '_ \| | '_ \ / _` |          
# | |_) | (_| \__ \ | | | | | | | (_| |          
# |____/_\__,_|___/_| |_|_|_| |_|\__, |          
#      | |                        __/ |          
#      | | __ _ _ __   __ _ _ __ |___/  ___  ___ 
#  _   | |/ _` | '_ \ / _` | '_ \ / _ \/ __|/ _ \
# | |__| | (_| | |_) | (_| | | | |  __/\__ \  __/
#  \____/ \__,_| .__/ \__,_|_| |_|\___||___/\___|
#              | |                               
#              |_|                               

n_chars=$1

COLOR_GREEN="[01;32m"
COLOR_RED="[01;31m"
COLOR_WHITE="[01;97m"
COLOR_END="[00m"

# Function to randomize the array
randomize_array() {
  shuffled_array=($(echo "${!japanese_words_and_data[@]}" | tr ' ' '\n' | shuf | tr '\n' ' '))
}

check_end() {
  if ((index >= ${#shuffled_array[@]})); then
    echo "End of the quiz. Your score is $score."
    exit
  fi
}

# Function to run the quiz loop
run_quiz() {
  score=0
  index=0

  while true; do
    japanese_word="${shuffled_array[$index]}"
    romaji_and_translation="${japanese_words_and_data[$japanese_word]}"

    if [[ $n_chars -gt 0 ]]; then
      if [[ $(echo -n "$japanese_word" | wc -m) -ne $n_chars ]]; then
        ((index++))
        check_end
        continue
      fi
    fi

    # Split the array element into Romaji and English translation
    IFS=':' read -r romaji english_translation <<< "$romaji_and_translation"

    read -p "What is the Romaji for '${COLOR_WHITE}$japanese_word${COLOR_END}'? " user_input

    # Make the comparison case-insensitive
    if [[ "${user_input,,}" == "${romaji,,}" ]]; then
      echo "${COLOR_GREEN}Correct!${COLOR_END}"
      [[ -n "$english_translation" ]] && echo "(English translation: $english_translation)."
      ((score++))
    else
      echo "${COLOR_RED}Incorrect!${COLOR_END} The Romaji for '${COLOR_WHITE}$japanese_word${COLOR_END}' is '${COLOR_WHITE}$romaji${COLOR_END}'."
    fi

    ((index++))
    check_end
  done
}

# Main script
randomize_array
run_quiz
